#!/bin/bash

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck disable=SC1091
source "$script_directory/../workspace-util"

session_name="example-streaming-app"
# shellcheck disable=SC2154
root_directory="${root_workspace_dir}/code/memgraph/example-streaming-app"
repo_url="git@github.com:memgraph/example-streaming-app.git"

if [[ $# -eq 0 ]]; then
    start_session "${session_name}" "${root_directory}" \
        "code" "" \
        "build" "" \
        "todo" "" \
        "todo" "" \
        "todo" "" \
        "memgraph" "" \
        "release" "" \
        "search" "" \
        "vcs" ""
    attach_session "${session_name}"
else
    workspace_action "$1" "${session_name}" "${script_directory}" "${root_directory}" "${repo_url}"
fi
