#!/bin/bash

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck disable=SC1091
source "$script_directory/../workspace-util"

session_name="gitbuda-memgraph"
# shellcheck disable=SC2154
root_directory="${root_workspace_dir}/code/memgraph/gitbuda-memgraph"
repo_url="git@github.com:gitbuda/memgraph.git"

if [[ $# -eq 0 ]]; then
    start_session "${session_name}" "${root_directory}" \
        "code" "" \
        "build" "" \
        "debug" "" \
        "run" "" \
        "name" "" \
        "name" "" \
        "name" "" \
        "search" "" \
        "vcs" ""
    attach_session "${session_name}"
else
    workspace_action "$1" "${session_name}" "${script_directory}" "${root_directory}" "${repo_url}"
fi
