#!/bin/bash

# shellcheck disable=SC1091
source "workspace-util"

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
session_name="mage"
# shellcheck disable=SC2154
root_directory="${root_workspace_dir}/code/mage"
repo_url="git@github.com:memgraph/mage.git"

if [[ $# -eq 0 ]]; then
    start_session "${session_name}" "${root_directory}" \
        "code" "vim" \
        "build" "" \
        "debug" "" \
        "test" "" \
        "run" "" \
        "client" "" \
        "release" "" \
        "search" "" \
        "vcs" ""
    attach_session "${session_name}"
else
    workspace_action "$1" "${session_name}" "${script_directory}" "${root_directory}" "${repo_url}"
fi
