#!/bin/bash

# shellcheck disable=SC1091
source "workspace-util"

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
session_name="memgraph"
# shellcheck disable=SC2154
root_directory="${root_workspace_dir}/code/memgraph"
repo_url="git@github.com:memgraph/memgraph.git"

if [[ $# -eq 0 ]]; then
    start_session "${session_name}" "${root_directory}" \
        "code" "nvim README.md" \
        "run" "" \
        "todo" "" \
        "todo" "" \
        "todo" "" \
        "server" "" \
        "release" "" \
        "search" "" \
        "vcs" ""
    attach_session "${session_name}"
else
    workspace_action "$1" "${session_name}" "${script_directory}" "${root_directory}" "${repo_url}"
fi
