#!/bin/bash

# shellcheck disable=SC1091
source "workspace-util"

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
session_name="orbicon"
# shellcheck disable=SC2154
root_directory="${root_workspace_dir}/code/memgraph/orbicon"
repo_url="git@github.com:memgraph/orbicon.git"

if [[ $# -eq 0 ]]; then
    start_session "${session_name}" "${root_directory}" \
        "code" "" \
        "build" "" \
        "todo" "" \
        "todo" "" \
        "todo" "" \
        "memgraph" "" \
        "release" "" \
        "search" "" \
        "vcs" ""
    attach_session "${session_name}"
else
    workspace_action "$1" "${session_name}" "${script_directory}" "${root_directory}" "${repo_url}"
fi
